server:
  port: 5005
  RunMode: debug
logger:
  filePath: ../logs/
  Encoding: json
  Level: debug
  logger: zerolog
cors:
  allowedOrigins: "*"
postgres:
  host: postgres_container  
  Port: 5432
  user: postgres
  password: admin
  dbName: car_sale_db
  sslMode: disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5
redis:
  host: localhost
  port: 6379
  password: password
  db : 0
  idleCheckFrequency: 300
  writeTimeout: 10
  readTimeout: 10
  dialTimeout : 10
  poolSize: 10
  poolTimeout: 30
  
otp:
  expireTime: 120
  digits: 6
  limiter: 100
jwt:
  secret: "mySecretKey"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 60
  refreshTokenExpireDuration: 60

 
  
